import Ajv2020 from 'ajv/dist/2020.js'; import schema from './schemas/map_structure.schema.json' with {type:'json'};
import {cp,mkdir,readFile,readdir,rm,stat,statfs,writeFile}from'node:fs/promises';import{existsSync}from'node:fs';import{basename,extname,join,resolve}from'node:path';import{randomUUID}from'node:crypto';import{spawn}from'node:child_process';import os from 'node:os';
import { CompositeDrawingAnalysisProvider, saveDrawingAnalysis } from './providers/drawing-analysis.js';
export { DrawingAnalysisProvider, DeterministicDrawingAnalysisProvider, FakeDrawingAnalysisProvider, LocalVisionDrawingAnalysisProvider } from './providers/drawing-analysis.js';
export { mapPositionToUnity, mapQuaternionToUnity, mapMatrixToUnity, mapNormalToUnity, mapTriangleWindingToUnity, unityPositionToMap } from './coordinate/transform.js';
export const STEPS=['preflight','input','analysis','structure_candidate','human_review','map_structure','blender_blockout','validation','unity_export','unity_import_validation','artifacts'],STATES=['PENDING','RUNNING','SUCCESS','FAILED','WAITING_USER','SKIPPED','CANCELLED'];const DS=['source','analysis','structure','blender','assets','renders','unity','validation','logs','checkpoints'],now=()=>new Date().toISOString(),wj=(p,v)=>writeFile(p,JSON.stringify(v,null,2)),rj=async p=>JSON.parse(await readFile(p,'utf8')),src=(f,t='INFERRED',c=.4)=>({source_type:t,confidence:c,source_reference:{source_file:f,page:1,bbox:null}});
export class ProvenanceError extends Error{} export function updateMeasuredValue(a,b,actor='automation'){if(a?.source?.source_type==='CONFIRMED'&&actor!=='human')throw new ProvenanceError('CONFIRMED values cannot be changed automatically');return{...b,source:{...(b.source??{}),source_type:actor==='human'?'CONFIRMED':b.source?.source_type??'INFERRED'}};}
export class Capability{constructor(available,reason=null,version=null,details={}){Object.assign(this,{available,reason,version,details})}}export class UnavailableProvider{constructor(name,reason='Not implemented in Phase 1'){Object.assign(this,{name,reason})}async capability(){return new Capability(false,this.reason,null,{provider:this.name})}}
const shell=(bin,args)=>new Promise(ok=>{const p=spawn(bin,args,{windowsHide:true});let out='';p.stdout?.on('data',x=>out+=x);p.on('error',()=>ok(null));p.on('close',code=>ok(code===0?out:null))});
const waitForFile=async(path,timeout=15000)=>{const until=Date.now()+timeout;while(Date.now()<until){if(existsSync(path))return true;await new Promise(resolve=>setTimeout(resolve,250));}return existsSync(path)};
export class FakeBlenderProvider{async capability(){return new Capability(true,null,'fake-1.0',{mode:'fake'})}async generate(p,m){await writeFile(join(p,'blender','map.blend'),'FAKE_BLEND\n'+JSON.stringify(m));const object_count=allObjects(m).length;await wj(join(p,'blender','metadata.json'),{provider:'fake',object_count});return{fake:true,object_count}}}export class RealBlenderProvider{constructor(path='blender'){this.path=path}async capability(){const o=await shell(this.path,['--version']);return o?new Capability(true,null,(o.match(/Blender\s+([^\s]+)/)||[])[1],{path:this.path,headless:true}):new Capability(false,'Blender CLI was not found',null,{path:this.path})}async generate(p,m){const c=await this.capability();if(!c.available)throw Error(c.reason);const data=join(p,'structure','map_structure.json').replace(/\\/g,'\\\\'),blend=join(p,'blender','map.blend').replace(/\\/g,'\\\\'),meta=join(p,'blender','metadata.json').replace(/\\/g,'\\\\'),script=join(p,'blender','blockout.py');await writeFile(script,`import bpy,json\nbpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)\nm=json.load(open(r'''${data}'''))\ndef add(i,p,s):\n bpy.ops.mesh.primitive_cube_add(location=p);o=bpy.context.object;o.name=i;o.scale=s\nfor o in m['objects']:add(o['id'],o['position'],o['scale'])\nfor b in m['buildings']:add(b['id'],b['position'],[b['scale'][0],b['scale'][1],b['height']/2])\nfor r in m['roads']:add(r['id'],r['points'][0],[r['width']/2,1,.05])\nbpy.ops.wm.save_as_mainfile(filepath=r'''${blend}''')\njson.dump({'provider':'real','object_count':len(bpy.context.scene.objects),'objects':[{'id':o.name,'position':list(o.location),'scale':list(o.scale),'rotation':list(o.rotation_euler)} for o in bpy.context.scene.objects]},open(r'''${meta}''','w'))`);const out=await shell(this.path,['--background','--python',script]);if(!out)throw Error('Blender headless generation failed');return rj(join(p,'blender','metadata.json'))}}
export class FakeUnityProvider{async capability(){return new Capability(true,null,'fake-1.0',{mode:'fake'})}async exportAndValidate(p,m){const objects=allObjects(m).map(o=>({id:o.id,position:mapToUnityPoint(o.position),rotation:mapToUnityQuaternion(eulerToQuaternion(o.rotation)),scale:o.scale}));await wj(join(p,'unity','map.fbx.json'),{format:'FBX',fake:true,objects});await wj(join(p,'unity','import_validation.json'),{provider:'fake',checks:objects.map(x=>({target_id:x.id,pass:true,message:'Fake test-mode validation'}))});return{fake:true}}}export class RealUnityProvider{constructor(path=null,project=null){Object.assign(this,{path,project})}async capability(){if(!this.path)return new Capability(false,'Unity executable is not configured');const o=await shell(this.path,['-version']);return o?new Capability(true,null,o.trim(),{path:this.path,project_path:this.project,batchmode:true}):new Capability(false,'Unity batchmode probe failed')}async exportAndValidate(p,m){const c=await this.capability();if(!c.available)throw Error(c.reason);await wj(join(p,'unity','map.export.json'),{format:'FBX',objects:allObjects(m).map(o=>({id:o.id,position:mapToUnityPoint(o.position)}))});return{fake:false,waiting_for_import_validation:true}}}
export function selectProvider(kind,mode='auto',s={}){const real=kind==='blender'?new RealBlenderProvider(s.blender_path):new RealUnityProvider(s.unity_path,s.unity_project_path),fake=kind==='blender'?new FakeBlenderProvider():new FakeUnityProvider();return{real,fake,mode}}export function providers(s={},mode='auto'){return{LLMProvider:new UnavailableProvider('LLMProvider','No local LLM configured'),AssetGenerationProvider:new UnavailableProvider('AssetGenerationProvider'),ImageSearchProvider:new UnavailableProvider('ImageSearchProvider'),UpperAIProvider:new UnavailableProvider('UpperAIProvider'),BlenderProvider:selectProvider('blender',s.blender_mode??mode,s),UnityProvider:selectProvider('unity',s.unity_mode??mode,s)}}
export async function preflight(p,settings={}){const capabilities={};for(const[k,v]of Object.entries(providers(settings,settings.mode))){capabilities[k]=v.real?{real:await v.real.capability(),fake:await v.fake.capability(),mode:v.mode}:await v.capability()}const fs=await statfs(p),gpu=await shell('nvidia-smi',['--query-gpu=name,memory.total,memory.free','--format=csv,noheader']);let internet={available:false,reason:'probe failed'};try{const r=await fetch('https://example.com',{signal:AbortSignal.timeout(2500)});internet={available:r.ok,status:r.status}}catch{}return{at:now(),capabilities,system:{os:`${os.type()} ${os.release()}`,cpu:os.cpus()?.[0]?.model??null,cpu_cores:os.cpus().length,ram_total:os.totalmem(),ram_available:os.freemem(),disk_total:Number(fs.blocks)*Number(fs.bsize),disk_free:Number(fs.bavail)*Number(fs.bsize),gpu:gpu?{available:true,details:gpu.trim()}: {available:false,reason:'nvidia-smi unavailable'},internet}}};
export async function createProject(root,name,s={}){const id='project_'+randomUUID().slice(0,8),path=join(resolve(root),id);await mkdir(path,{recursive:true});await Promise.all(DS.map(d=>mkdir(join(path,d),{recursive:true})));const project={project_id:id,project_name:name,created_at:now(),provider_settings:{mode:s.mode??'auto',...s},default_max_retry:3,validation_tolerance:s.validation_tolerance??.01,human_review_confidence_threshold:s.human_review_confidence_threshold??.8,performance_profile:'Prototype',unity_export_format:'FBX',paused:false,cancelled:false,steps:Object.fromEntries(STEPS.map(x=>[x,{state:'PENDING',updated_at:now()}]))};await wj(join(path,'project.json'),project);return{path,project}}export const loadProject=p=>rj(join(p,'project.json')),saveProject=(p,x)=>wj(join(p,'project.json'),x),appendLog=(p,e,x={})=>writeFile(join(p,'logs','events.jsonl'),JSON.stringify({at:now(),event:e,...x})+'\n',{flag:'a'});export async function setStep(p,s,state,x={}){const j=await loadProject(p);j.steps[s]={...j.steps[s],state,updated_at:now(),...x};await saveProject(p,j);await appendLog(p,'step_state',{step:s,state,...x});if(state==='SUCCESS')await wj(join(p,'checkpoints',`${Date.now()}-${s}.json`),{step:s,project:j,created_at:now()});return j}export async function resume(p){const j=await loadProject(p);j.paused=false;await saveProject(p,j);return j}export async function pauseProject(p){const j=await loadProject(p);j.paused=true;await saveProject(p,j);return j}export async function cancelProject(p){const j=await loadProject(p);j.cancelled=true;for(const s of STEPS)if(['PENDING','RUNNING'].includes(j.steps[s].state))j.steps[s].state='CANCELLED';await saveProject(p,j);return j}export async function retry(p,s,k='local_fix'){const j=await loadProject(p),n=(j.steps[s].retry_counters?.[k]??0)+1;return setStep(p,s,n>=j.default_max_retry?'WAITING_USER':'PENDING',{retry_counters:{...(j.steps[s].retry_counters??{}),[k]:n},requires_human_decision:n>=j.default_max_retry})}
export async function invalidateFrom(p,s){const j=await loadProject(p),i=STEPS.indexOf(s);for(const x of STEPS.slice(i)){j.steps[x]={...j.steps[x],state:'PENDING',stale:true,invalidated_at:now(),invalidated_by:s};for(const f of ({analysis:['analysis/drawing_analysis.json'],structure_candidate:['structure/candidate.json'],map_structure:['structure/map_structure.json'],blender_blockout:['blender/map.blend','blender/metadata.json','blender/scene_measurement.json','blender/blockout_metadata.json'],validation:['validation/deterministic.json'],unity_export:['unity/map.fbx.json','unity/map.export.json'],unity_import_validation:['unity/import_validation.json']}[x]??[]))await rm(join(p,f),{force:true})}await saveProject(p,j);return j}
function png(b){return b.subarray(0,8).toString('hex')==='89504e470d0a1a0a'?{width:b.readUInt32BE(16),height:b.readUInt32BE(20),color_mode:b[25]}:null}function jpeg(b){let i=2;while(i<b.length){if(b[i]!==255){i++;continue}const m=b[i+1],n=b.readUInt16BE(i+2);if(m>=192&&m<=195)return{height:b.readUInt16BE(i+5),width:b.readUInt16BE(i+7),color_mode:'jpeg'};i+=2+n}return null}async function pdf(b){const api=await import('pdfjs-dist/legacy/build/pdf.mjs'),d=await api.getDocument({data:new Uint8Array(b)}).promise,p=[];for(let i=1;i<=d.numPages;i++){const v=(await d.getPage(i)).getViewport({scale:1});p.push({width:v.width,height:v.height})}return{page_count:d.numPages,pages:p,render_dpi:72}}
export async function importInput(p,file){const e=extname(file).toLowerCase();if(!['.png','.jpg','.jpeg','.pdf'].includes(e))throw Error('Only PNG, JPG, JPEG and PDF are supported');const target=join(p,'source',basename(file));await cp(file,target,{force:true});return inputMeta(p,target)}export async function importInputData(p,name,data){const target=join(p,'source',basename(name));await writeFile(target,data);return inputMeta(p,target)}async function inputMeta(p,target){const b=await readFile(target),e=extname(target).toLowerCase(),d=e==='.png'?png(b):e==='.pdf'?await pdf(b):jpeg(b);if(!d)throw Error('Input file integrity or format is invalid');const meta={source_file:basename(target),mime:e==='.pdf'?'application/pdf':`image/${e.slice(1).replace('jpg','jpeg')}`,page_count:d.page_count??1,...d,byte_size:b.length,ocr:{available:false,reason:'OCR provider unavailable'},source_reference:{source_file:basename(target),page:1,bbox:null},extracted_at:now()};await wj(join(p,'analysis','input_metadata.json'),meta);return meta}
const ajv=new Ajv2020({allErrors:true,strict:false}),check=ajv.compile(schema);export function validateSchema(m){const valid=check(m);return{valid,errors:valid?[]:check.errors.map(x=>`${x.instancePath||'/'} ${x.message}`)}}export function allObjects(m){return[...m.objects,...m.roads.map(r=>({id:r.id,position:r.points[0],rotation:r.rotation,scale:[r.width,1,.1]})),...m.buildings.map(b=>({id:b.id,position:b.position,rotation:b.rotation,scale:b.scale}))]}export function semanticValidate(m){const e=[],seen=new Set;for(const o of allObjects(m)){if(seen.has(o.id))e.push('duplicate object: '+o.id);seen.add(o.id);if(o.scale.some(x=>x<0))e.push('negative scale: '+o.id)}return{valid:!e.length,errors:e}}export function validateMap(m){const a=validateSchema(m),b=semanticValidate(m);return{valid:a.valid&&b.valid,errors:[...a.errors,...b.errors]}}export function deterministicValidate(m,t=.01){const r=[];for(const x of m.roads)r.push({target_id:x.id,expected:'road width > 0',actual:x.width,tolerance:t,pass:x.width>t,message:'Road width'});for(const x of m.buildings)r.push({target_id:x.id,expected:'building height > 0',actual:x.height,tolerance:t,pass:x.height>t,message:'Building height'});for(const x of allObjects(m))r.push({target_id:x.id,expected:'non-negative scale',actual:x.scale,tolerance:t,pass:x.scale.every(y=>y>=0),message:'Scale'});return{pass:r.every(x=>x.pass),results:r}}
export function validateBlenderScene(map, scene, tolerance=.01){const actual=scene.objects??[], expected=allObjects(map), results=[];results.push({target_id:'scene',property:'object_count',expected:expected.length,actual:actual.length,tolerance:0,pass:expected.length===actual.length,message:'Object count'});const seen=new Set;for(const o of actual){results.push({target_id:o.id,property:'duplicate',expected:false,actual:seen.has(o.id),tolerance:0,pass:!seen.has(o.id),message:'Duplicate object'});seen.add(o.id)}for(const e of expected){const a=actual.find(x=>x.id===e.id);results.push({target_id:e.id,property:'exists',expected:true,actual:!!a,tolerance:0,pass:!!a,message:'Missing object'});if(!a)continue;const pos=e.position??[0,0,0];results.push({target_id:e.id,property:'position',expected:pos,actual:a.position,tolerance,pass:pos.every((v,i)=>Math.abs(v-a.position[i])<=tolerance),message:'World position'});const b=map.buildings.find(x=>x.id===e.id);if(b){results.push({target_id:e.id,property:'height',expected:b.height,actual:a.dimensions[2],tolerance,pass:Math.abs(b.height-a.dimensions[2])<=tolerance,message:'Building height'});results.push({target_id:e.id,property:'width_depth',expected:[Math.max(...b.footprint.map(p=>p[0]))-Math.min(...b.footprint.map(p=>p[0])),Math.max(...b.footprint.map(p=>p[1]))-Math.min(...b.footprint.map(p=>p[1]))],actual:a.dimensions.slice(0,2),tolerance,pass:true,message:'Building footprint bounds'});}const r=map.roads.find(x=>x.id===e.id);if(r)results.push({target_id:e.id,property:'road_width',expected:r.width,actual:a.dimensions[1],tolerance,pass:Math.abs(r.width-a.dimensions[1])<=tolerance,message:'Road width'});}return{provider_name:'BlenderSceneValidator',pass:results.every(x=>x.pass),results};}
const clean=n=>Object.is(n,-0)?0:n;export const mapToUnityPoint=([x,y,z])=>[x,z,clean(-y)],mapToUnityNormal=([x,y,z])=>[x,z,clean(-y)],flipTriangleWinding=([a,b,c])=>[a,c,b];export function eulerToQuaternion([x,y,z]){const d=Math.PI/360,cx=Math.cos(x*d),sx=Math.sin(x*d),cy=Math.cos(y*d),sy=Math.sin(y*d),cz=Math.cos(z*d),sz=Math.sin(z*d);return[sx*cy*cz-cx*sy*sz,cx*sy*cz+sx*cy*sz,cx*cy*sz-sx*sy*cz,cx*cy*cz+sx*sy*sz]}export const mapToUnityQuaternion=([x,y,z,w])=>[clean(-x),clean(-z),y,w];
export const unityPoint=mapToUnityPoint;
export async function candidate(p){const m=await rj(join(p,'analysis','input_metadata.json')),w=m.width??m.pages?.[0]?.width??100,h=m.height??m.pages?.[0]?.height??100,z=Math.max(10,Math.round(Math.max(w,h)/10)),s=src(m.source_file);const c={version:'1.1',project:{id:(await loadProject(p)).project_id},coordinate_system:{handedness:'right-handed',up_axis:'Z'},units:'meter',world_origin:[0,0,0],terrain:[],roads:[{id:'road-1',points:[[-z/2,0,0],[z/2,0,0]],width:Math.max(2,Math.round(z/20)),elevation:0,rotation:[0,0,0],source:s}],buildings:[{id:'building-1',footprint:[[0,0,0],[z/4,0,0],[z/4,z/4,0],[0,z/4,0]],height:3,floors:1,position:[z/6,z/6,1.5],rotation:[0,0,0],scale:[z/8,z/8,1.5],source:s}],objects:[{id:'ground-1',type:'ground',asset_id:null,position:[0,0,0],rotation:[0,0,0],scale:[z,z,.1],source:src(m.source_file,'GENERATED',1)}],zones:[],metadata:{unresolved_items:[{field:'map_scale',reason:'Derived from input dimensions',source:s}],analysis_input:m.source_file}};const v=validateSchema(c);if(!v.valid)throw Error(v.errors.join('; '));await wj(join(p,'structure','candidate.json'),c);return c}
export async function buildStructureCandidate(p){const a=await rj(join(p,'analysis','drawing_analysis.json')),m=await rj(join(p,'analysis','input_metadata.json')),z=Math.max(10,Math.round(Math.max(m.width??100,m.height??100)/10)),s=src(m.source_file,'INFERRED',a.confidence);const roads=a.detected.roads.map((r,i)=>({id:`road-${i+1}`,points:r.points.map(([x,y])=>[x/z,y/z,0]),width:r.width_candidate,elevation:0,rotation:[0,0,0],source:s}));const buildings=a.detected.buildings.map((b,i)=>{const f=b.footprint.map(([x,y])=>[x/z,y/z,0]);return{id:`building-${i+1}`,footprint:f,height:b.height_candidate,floors:1,position:[f[0][0],f[0][1],b.height_candidate/2],rotation:[0,0,0],scale:[1,1,1],source:s}});const c={version:'1.1',project:{id:(await loadProject(p)).project_id},coordinate_system:{handedness:'right-handed',up_axis:'Z'},units:'meter',world_origin:[0,0,0],terrain:[],roads,buildings,objects:[{id:'ground-1',type:'ground',asset_id:null,position:[0,0,0],rotation:[0,0,0],scale:[z,z,.1],source:src(m.source_file,'GENERATED',1)}],zones:[],metadata:{unresolved_items:[{field:'map_scale',reason:'No confirmed scale notation',source:s}],analysis_input:m.source_file,analysis_provider:a.provider}};const v=validateSchema(c);if(!v.valid)throw Error(v.errors.join('; '));await wj(join(p,'structure','candidate.json'),c);return c}
export async function review(p,a,item={}){const f=join(p,'structure','candidate.json');if(!existsSync(f))throw Error('Structure Candidate is required for human review');const c=await rj(f);if(a==='approve'||a==='continue_unresolved'){if(a==='continue_unresolved')c.metadata.unresolved_items.push(item);const v=validateMap(c);if(!v.valid)throw Error(v.errors.join('; '));await wj(f,c);await wj(join(p,'structure','map_structure.json'),c);return setStep(p,'human_review','SUCCESS',a==='continue_unresolved'?{unresolved:true}:{})}if(a==='correct'){const target=c[item.collection??'buildings']?.find(x=>x.id===item.id);if(!target)throw Error('Review target not found');const before=target[item.field],old=target.field_provenance?.[item.field];if(old?.source_type==='CONFIRMED'&&item.actor!=='human')throw new ProvenanceError('CONFIRMED field requires human decision');target[item.field]=item.value;target.field_provenance={...(target.field_provenance??{}),[item.field]:{value:item.value,source_type:'CONFIRMED',confidence:1,source_reference:[{source_file:'human-review'}]}};target.change_history=[...(target.change_history??[]),{at:now(),field:item.field,before,value:item.value}];await wj(f,c);return setStep(p,'human_review','WAITING_USER')}if(a==='reestimate'){const target=c[item.collection??'buildings']?.find(x=>x.id===item.id);if(target?.field_provenance?.[item.field]?.source_type==='CONFIRMED')throw new ProvenanceError('CONFIRMED field requires human decision');c.metadata.reestimated_item=item.id??null;await wj(f,c);return setStep(p,'human_review','WAITING_USER')}throw Error('Unknown review action')}
export async function run(p, from='preflight') {
  for (const step of STEPS.slice(STEPS.indexOf(from))) {
    const project=await loadProject(p); if(project.paused||project.cancelled||project.steps[step].state==='CANCELLED') break;
    try {
      await setStep(p,step,'RUNNING');
      if(step==='preflight') await wj(join(p,'validation','preflight.json'),await preflight(p,project.provider_settings));
      if(step==='input'&&!existsSync(join(p,'analysis','input_metadata.json'))) { await setStep(p,step,'WAITING_USER',{requires_human_decision:true,message:'Input required'}); break; }
      if(step==='analysis') { const m=await rj(join(p,'analysis','input_metadata.json')); await saveDrawingAnalysis(p,await new CompositeDrawingAnalysisProvider().analyze(p,m)); }
      if(step==='structure_candidate') await buildStructureCandidate(p);
      if(step==='human_review') { await setStep(p,step,'WAITING_USER',{requires_human_decision:true}); break; }
      if(step==='map_structure') { const v=validateMap(await rj(join(p,'structure','map_structure.json'))); if(!v.valid) throw Error(v.errors.join('; ')); }
      if(step==='blender_blockout') { const m=await rj(join(p,'structure','map_structure.json')),x=selectProvider('blender',project.provider_settings.blender_mode??project.provider_settings.mode,project.provider_settings),cap=await x.real.capability(); if(!cap.available&&x.mode!=='fake'){await setStep(p,step,'WAITING_USER',{requires_human_decision:true,message:cap.reason});break;} await(x.mode==='fake'?x.fake:x.real).generate(p,m); }
      if(step==='validation') { const m=await rj(join(p,'structure','map_structure.json')),base=deterministicValidate(m,project.validation_tolerance),scenePath=join(p,'blender','scene_measurement.json'); if(!existsSync(scenePath))throw Error('Blender scene measurement is required'); const measured=validateBlenderScene(m,await rj(scenePath),project.validation_tolerance);const v={pass:base.pass&&measured.pass,results:[...base.results,...measured.results],blender_scene:measured}; await wj(join(p,'validation','deterministic.json'),v); if(!v.pass){await retry(p,step,'local_fix');break;} }
      if(step==='unity_export') { const m=await rj(join(p,'structure','map_structure.json')),v=await rj(join(p,'validation','deterministic.json')); if(!v.pass)throw Error('Unity export blocked: deterministic validation failed'); const x=selectProvider('unity',project.provider_settings.unity_mode??project.provider_settings.mode,project.provider_settings),cap=await x.real.capability(); if(!cap.available&&x.mode!=='fake'){await setStep(p,step,'WAITING_USER',{requires_human_decision:true,message:cap.reason});break;} await(x.mode==='fake'?x.fake:x.real).exportAndValidate(p,m); }
      if(step==='unity_import_validation' && (project.provider_settings.unity_mode??project.provider_settings.mode)!=='fake') { const f=join(p,'unity','import_validation.json'); if(!existsSync(f))throw Error('Unity validation JSON is required'); const v=await rj(f); if(v.provider_mode!=='real'||v.is_fake||!v.import_success||!v.pass)throw Error('Unity validation gate failed'); }
      await setStep(p,step,'SUCCESS');
    } catch(e) { await setStep(p,step,'FAILED',{error:e.message}); await appendLog(p,'step_error',{step,error:e.message}); break; }
  }
  return loadProject(p);
}

// Phase 1.3.1B: replace the early prototype generator without changing the
// provider interface. This script is run only by the explicitly selected real provider.
RealBlenderProvider.prototype.generate = async function(project, map) {
  const capability = await this.capability(); if (!capability.available) throw Error(capability.reason);
  const data=join(project,'structure','map_structure.json').replace(/\\/g,'\\\\');
  const blend=join(project,'blender','map.blend').replace(/\\/g,'\\\\');
  const fbx=join(project,'blender','map.fbx').replace(/\\/g,'\\\\');
  const measure=join(project,'blender','scene_measurement.json').replace(/\\/g,'\\\\');
  const metadata=join(project,'blender','blockout_metadata.json').replace(/\\/g,'\\\\');
  const script=join(project,'blender','blockout.py');
  await writeFile(script,`import bpy,json,os\nbpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)\nm=json.load(open(r'''${data}''')); warnings=[]\ndef mesh(name,vs,fs):\n d=bpy.data.meshes.new(name);d.from_pydata(vs,[],fs);d.update();o=bpy.data.objects.new(name,d);bpy.context.collection.objects.link(o);return o\ndef building(b):\n f=b.get('footprint',[]);h=b.get('height',3)\n if len(f)<3: warnings.append({'target_id':b['id'],'fallback_used':True,'reason':'missing footprint'});bpy.ops.mesh.primitive_cube_add();o=bpy.context.object;o.name=b['id'];return o\n vs=[(p[0],p[1],p[2]) for p in f]+[(p[0],p[1],p[2]+h) for p in f];n=len(f);fs=[list(range(n)),list(range(n,2*n))]+[[i,(i+1)%n,(i+1)%n+n,i+n] for i in range(n)];o=mesh(b['id'],vs,fs);o.location=b.get('position',[0,0,0]);o.rotation_euler=b.get('rotation',[0,0,0]);o.scale=b.get('scale',[1,1,1]);return o\ndef road(r):\n c=bpy.data.curves.new(r['id'],'CURVE');c.dimensions='3D';c.bevel_depth=r['width']/2;c.resolution_u=1;s=c.splines.new('POLY');pts=r['points'];s.points.add(len(pts)-1)\n for p,v in zip(s.points,pts):p.co=(v[0],v[1],v[2]+r.get('elevation',0),1)\n o=bpy.data.objects.new(r['id'],c);bpy.context.collection.objects.link(o);bpy.context.view_layer.objects.active=o;o.select_set(True);bpy.ops.object.convert(target='MESH');return bpy.context.object\nfor o in m.get('objects',[]):\n bpy.ops.mesh.primitive_plane_add(size=2,location=o.get('position',[0,0,0]));x=bpy.context.object;x.name=o['id'];x.scale=o.get('scale',[1,1,1])\nfor b in m.get('buildings',[]):building(b)\nfor r in m.get('roads',[]):road(r)\nme=[]\nfor o in bpy.context.scene.objects:\n d=o.dimensions;me.append({'id':o.name,'type':o.type,'position':list(o.location),'rotation_quaternion':list(o.rotation_quaternion),'scale':list(o.scale),'world_matrix':[list(x) for x in o.matrix_world],'bounding_box':[list(x) for x in o.bound_box],'dimensions':list(d),'vertex_count':len(o.data.vertices) if o.type=='MESH' else 0,'polygon_count':len(o.data.polygons) if o.type=='MESH' else 0})\njson.dump({'provider_name':'RealBlenderProvider','provider_mode':'real','is_fake':False,'objects':me,'warnings':warnings},open(r'''${measure}''','w'))\njson.dump({'provider_name':'RealBlenderProvider','provider_mode':'real','is_fake':False,'fallbacks':warnings,'object_count':len(me)},open(r'''${metadata}''','w'))\nbpy.ops.wm.save_as_mainfile(filepath=r'''${blend}''');bpy.ops.export_scene.fbx(filepath=r'''${fbx}''')`);
  const output=await shell(this.path,['--background','--python',script]); if(!output) throw Error('Blender headless generation failed');
  return rj(join(project,'blender','blockout_metadata.json'));
};

const UNITY_2022 = 'C:\\Program Files\\Unity\\Hub\\Editor\\2022.3.62f3\\Editor\\Unity.exe';
RealUnityProvider.prototype.capability = async function() { const exe=this.path||UNITY_2022, out=await shell(exe,['-version']); return out?new Capability(true,null,out.trim(),{path:exe,batchmode:true,validation_project:true}):new Capability(false,'Unity 2022.3.62f3 Batchmode is unavailable',null,{path:exe}); };
RealUnityProvider.prototype.exportAndValidate = async function(project, map) {
  const cap=await this.capability(); if(!cap.available)throw Error(cap.reason); const validation=join(project,'unity','validation_project'), assets=join(validation,'Assets','Smoke'), editor=join(validation,'Assets','Editor'); await mkdir(assets,{recursive:true});await mkdir(editor,{recursive:true});await mkdir(join(validation,'ProjectSettings'),{recursive:true});
  const fbx=join(project,'blender','map.fbx');if(!existsSync(fbx))throw Error('FBX export is required before Unity import');await cp(fbx,join(assets,'map.fbx'),{force:true});
  await writeFile(join(validation,'ProjectSettings','ProjectVersion.txt'),`m_EditorVersion: 2022.3.62f3\n`.replace(/^(?=.)/m,''));
  const result=join(project,'unity','import_validation.json').replace(/\\/g,'\\\\');
  await writeFile(join(editor,'MapValidation.cs'),`using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;[Serializable]public class R{public string provider_name="RealUnityProvider",provider_mode="real";public bool is_fake=false,import_success,pass;public int mesh_count;public string unity_version;public string[] critical_checks;public static void Run(){AssetDatabase.Refresh();var p="Assets/Smoke/map.fbx";var root=AssetDatabase.LoadAssetAtPath<GameObject>(p);var ms=AssetDatabase.LoadAllAssetsAtPath(p).OfType<Mesh>().ToArray();var ok=root!=null&&ms.Length>0&&ms.All(x=>x.normals.Length==x.vertexCount);var r=new R{import_success=ok,pass=ok,mesh_count=ms.Length,unity_version=Application.unityVersion,critical_checks=ok?new string[0]:new[]{"Missing mesh or normals"}};File.WriteAllText(@"${result}",JsonUtility.ToJson(r,true));EditorApplication.Exit(ok?0:2);}}`);
  // R.Run exits explicitly.  Omitting -quit lets the second fresh-project pass
  // execute after Unity has compiled the newly written Editor assembly.
  const out=await shell(cap.details.path,['-batchmode','-nographics','-projectPath',validation,'-executeMethod','R.Run','-logFile',join(project,'unity','unity_batchmode.log')]);
  if(!existsSync(join(project,'unity','import_validation.json'))) { await shell(cap.details.path,['-batchmode','-nographics','-projectPath',validation,'-executeMethod','R.Run','-logFile',join(project,'unity','unity_batchmode.log')]); }
  if(!existsSync(join(project,'unity','import_validation.json')))throw Error('Unity did not produce import_validation.json');const json=await rj(join(project,'unity','import_validation.json'));if(json.provider_mode!=='real'||json.is_fake||!json.import_success||!json.pass)throw Error('Unity critical validation failed');return json;
};
FakeBlenderProvider.prototype.generate = async function(project,map){await writeFile(join(project,'blender','map.blend'),'FAKE_BLEND\n'+JSON.stringify(map));const objects=allObjects(map).map(o=>{const b=map.buildings.find(x=>x.id===o.id),r=map.roads.find(x=>x.id===o.id);return{id:o.id,position:o.position,rotation_quaternion:[1,0,0,0],scale:o.scale,world_matrix:[],bounding_box:[],dimensions:b?[Math.max(...b.footprint.map(p=>p[0]))-Math.min(...b.footprint.map(p=>p[0])),Math.max(...b.footprint.map(p=>p[1]))-Math.min(...b.footprint.map(p=>p[1])),b.height]:r?[0,r.width,0]:[0,0,0],vertex_count:0,polygon_count:0}});await wj(join(project,'blender','scene_measurement.json'),{provider_name:'FakeBlenderProvider',provider_mode:'fake',is_fake:true,objects});await wj(join(project,'blender','metadata.json'),{provider:'fake',object_count:objects.length});return{fake:true,object_count:objects.length};};
const BLENDER_51='C:\\Program Files\\Blender Foundation\\Blender 5.1\\blender.exe';const oldBlenderCapability=RealBlenderProvider.prototype.capability;RealBlenderProvider.prototype.capability=async function(){if(this.path==='blender')this.path=BLENDER_51;return oldBlenderCapability.call(this);};

// Phase 2D: keep the schema backward compatible while enforcing relationships
// only when the optional formal asset-requirement stage is present.
const phase1ValidateMap=validateMap;
validateMap=m=>{const base=phase1ValidateMap(m),errors=[...base.errors],requirements=m.asset_requirements||[];if(requirements.length){const assets=new Map,objects=new Map((m.objects||[]).map(o=>[o.id,o]));for(const r of requirements){if(assets.has(r.asset_id))errors.push('duplicate asset requirement: '+r.asset_id);assets.set(r.asset_id,r);if(!r.target_dimensions?.every(x=>Number.isFinite(x)&&x>0))errors.push('invalid asset target dimensions: '+r.asset_id);if(r.reference_image!==null&&(!r.reference_image||typeof r.reference_image!=='string'))errors.push('invalid asset reference: '+r.asset_id);if(!['replace_ready','manual','keep_placeholder'].includes(r.replacement_policy??'replace_ready'))errors.push('invalid replacement policy: '+r.asset_id);for(const id of r.object_ids||[]){const object=objects.get(id);if(!object)errors.push('asset binding references missing object: '+id);else if(object.asset_id!==r.asset_id)errors.push('asset binding mismatch: '+id)}}for(const object of m.objects||[])if(object.asset_id&&!assets.has(object.asset_id))errors.push('object references missing asset requirement: '+object.id)}return{valid:errors.length===0,errors};};

// A new validation project has no compiled Editor assembly on its first launch.
// InitializeOnLoad schedules the check after that compilation/domain reload.
RealUnityProvider.prototype.exportAndValidate=async function(project,map){const cap=await this.capability();if(!cap.available)throw Error(cap.reason);const validation=join(project,'unity','validation_project'),assets=join(validation,'Assets','Smoke'),editor=join(validation,'Assets','Editor');await mkdir(assets,{recursive:true});await mkdir(editor,{recursive:true});await mkdir(join(validation,'ProjectSettings'),{recursive:true});const fbx=join(project,'blender','map.fbx');if(!existsSync(fbx))throw Error('FBX export is required before Unity import');await cp(fbx,join(assets,'map.fbx'),{force:true});await writeFile(join(validation,'ProjectSettings','ProjectVersion.txt'),'m_EditorVersion: 2022.3.62f3\n');const result=join(project,'unity','import_validation.json').replace(/\\/g,'\\\\'),resultFile=join(project,'unity','import_validation.json');await writeFile(join(editor,'MapValidation.cs'),`using System;using System.IO;using System.Linq;using UnityEditor;using UnityEngine;[Serializable]public class R{public string provider_name="RealUnityProvider",provider_mode="real";public bool is_fake=false,import_success,pass;public int mesh_count;public string unity_version;public string[] critical_checks;[InitializeOnLoadMethod]static void Boot(){EditorApplication.delayCall+=Run;}public static void Run(){AssetDatabase.Refresh();var p="Assets/Smoke/map.fbx";var root=AssetDatabase.LoadAssetAtPath<GameObject>(p);var ms=AssetDatabase.LoadAllAssetsAtPath(p).OfType<Mesh>().ToArray();var ok=root!=null&&ms.Length>0&&ms.All(x=>x.normals.Length==x.vertexCount);var r=new R{import_success=ok,pass=ok,mesh_count=ms.Length,unity_version=Application.unityVersion,critical_checks=ok?new string[0]:new[]{"Missing mesh or normals"}};File.WriteAllText(@"${result}",JsonUtility.ToJson(r,true));EditorApplication.Exit(ok?0:2);}}`);const args=['-batchmode','-nographics','-projectPath',validation,'-logFile',join(project,'unity','unity_batchmode.log')];await shell(cap.details.path,args);if(!await waitForFile(resultFile))await shell(cap.details.path,args);if(!await waitForFile(resultFile))await shell(cap.details.path,[...args,'-executeMethod','R.Run']);if(!await waitForFile(resultFile))throw Error('Unity did not produce import_validation.json');const output=await rj(resultFile);if(output.provider_mode!=='real'||output.is_fake||!output.import_success||!output.pass)throw Error('Unity critical validation failed');return output;};

// Human review may add a semantic placement to the candidate; this is the
// reviewed Phase 1 path for assets that analysis cannot classify automatically.
const phase1Review=review;
review=async function(project,action,item={}){if(action!=='add_object')return phase1Review(project,action,item);const file=join(project,'structure','candidate.json');if(!existsSync(file))throw Error('Structure Candidate is required for human review');const map=await rj(file),object=item.object;if(!object||!object.id||!['placeholder','primitive'].includes(object.type)||!Array.isArray(object.position)||!Array.isArray(object.rotation)||!Array.isArray(object.scale))throw Error('A complete reviewed semantic object is required');if(map.objects.some(x=>x.id===object.id)||allObjects(map).some(x=>x.id===object.id))throw Error('Reviewed semantic object ID already exists');const reviewed={...object,asset_id:null,source:object.source||src('human-review','CONFIRMED',1)};map.objects.push(reviewed);const valid=validateMap(map);if(!valid.valid)throw Error(valid.errors.join('; '));await wj(file,map);return setStep(project,'human_review','WAITING_USER',{requires_human_decision:true,last_review_action:'add_object'});};

// Road curve points are stored in mesh/world coordinates; their Blender object
// origin remains zero, unlike ordinary placed objects.
const phase1AllObjects=allObjects;
allObjects=m=>[...m.objects,...m.roads.map(r=>({id:r.id,position:[0,0,0],rotation:r.rotation,scale:[r.width,1,.1]})),...m.buildings.map(b=>({id:b.id,position:b.position,rotation:b.rotation,scale:b.scale}))];