import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createProject } from '../core.js';
import { MapProductionApplicationService } from '../assets/map-production-application-service.js';
import { MapProductionService } from '../assets/production.js';
import { ReferenceOrchestrator, ReferenceRegistry } from '../assets/reference-system.js';
import { WikimediaCommonsReferenceProvider } from '../assets/wikimedia-reference-provider.js';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+ZyXSUwAAAABJRU5ErkJggg==','base64');
const source={source_type:'GENERATED',confidence:1,source_reference:{source_file:'wikimedia-e2e.json'}};
const map={version:'1.1',project:{id:'wikimedia-e2e'},coordinate_system:{handedness:'right-handed',up_axis:'Z'},units:'meter',world_origin:[0,0,0],terrain:[],roads:[{id:'road-1',points:[[0,0,0],[5,0,0]],width:1,elevation:0,rotation:[0,0,0],source}],buildings:[{id:'building-1',footprint:[[0,0,0],[2,0,0],[2,2,0],[0,2,0]],height:3,floors:1,position:[1,1,1.5],rotation:[0,0,0],scale:[1,1,1],source}],objects:[{id:'ground-1',type:'ground',asset_id:null,position:[0,0,0],rotation:[0,0,0],scale:[10,10,.1],source}],zones:[],metadata:{unresolved_items:[]}};
const decisions={decisions:[{object_id:'ground-1',production_mode:'PROCEDURAL'},{object_id:'road-1',production_mode:'PROCEDURAL'},{object_id:'building-1',production_mode:'GENERATED_ASSET'}]};
const measurement={objects:[{id:'ground-1',position:[0,0,0],dimensions:[10,10,.1]},{id:'road-1',position:[0,0,0],dimensions:[5,1,.1]},{id:'building-1',position:[1,1,1.5],dimensions:[2,2,3]}]};
const response=(body,options={})=>new Response(body,options);

test('Application Service reaches READY with real Wikimedia provider and mocked HTTP',async()=>{
  const root=await mkdtemp(join(tmpdir(),'full-production-wikimedia-')),{path:project}=await createProject(root,'wikimedia-e2e'),bridge=join(project,'production_bridge'),calls={http:0,asset:0,material:0,blender:0,export:0,unity:0};await Promise.all([mkdir(join(project,'structure'),{recursive:true}),mkdir(bridge,{recursive:true})]);await writeFile(join(project,'structure','map_structure.json'),JSON.stringify(map));
  const assets={asset_requirements:[{asset_id:'asset-building',object_ids:['building-1'],generation_mode:'generated_asset',target_dimensions:[2,2,3],generation_profile:'Prototype',provider_preferences:['fake'],reference_requirement_id:'ref-building',status:'APPROVED',material_requirement:{material_id:'material-building'}}]},refs={reference_requirements:[{reference_requirement_id:'ref-building',mode:'AUTO_ACQUIRE',status:'PENDING',category:'building',purpose:'GEOMETRY',search_terms:['architecture'],minimum_resolution:[1,1],required:true}]};for(const [file,value]of[['production_readiness.json',{state:'READY'}],['binding_review.json',decisions],['asset_requirements.json',assets],['reference_requirements.json',refs]])await writeFile(join(bridge,file),JSON.stringify(value));
  const fetchImpl=async url=>{calls.http++;const parsed=new URL(url);if(parsed.hostname==='upload.wikimedia.org')return response(png,{headers:{'content-type':'image/png','content-length':String(png.length)}});if(parsed.searchParams.get('list')==='search')return response(JSON.stringify({query:{search:[{title:'File:Building.png'}]}}),{headers:{'content-type':'application/json'}});return response(JSON.stringify({query:{pages:{'1':{pageid:1,title:'File:Building.png',imageinfo:[{url:'https://upload.wikimedia.org/building.png',thumburl:'https://upload.wikimedia.org/building.png',descriptionurl:'https://commons.wikimedia.org/wiki/File:Building.png',width:1200,height:800,mime:'image/png',extmetadata:{LicenseShortName:{value:'CC0'},Artist:{value:'Example'}}}]}}}}),{headers:{'content-type':'application/json'}})};
  const registry=await new ReferenceRegistry(project).init(),local={searches:0,async search(){this.searches++;return[]}},provider=new WikimediaCommonsReferenceProvider({project,fetchImpl}),references=new ReferenceOrchestrator(project,{registry,localProvider:local,webProvider:provider});
  const app=new MapProductionApplicationService({productionServiceFactory:target=>new MapProductionService(target,{referenceOrchestrator:references,assetOrchestrator:{run:async received=>{calls.asset++;assert.ok(received.asset_requirements[0].reference_image);assert.ok(received.asset_requirements[0].reference_fingerprint);return{state:'READY',assets:[]}}},materialOrchestrator:{run:async()=>{calls.material++;const dir=join(target,'materials');await mkdir(dir,{recursive:true});await Promise.all(['material_plan.json','material_report.json','material_validation.json'].map(f=>writeFile(join(dir,f),'{}')));return{pass:true}}},blenderFinalizer:{run:async()=>{calls.blender++;return{scene_measurement:measurement}}},exportService:{run:async()=>{calls.export++;const f=join(target,'blender','map.fbx');await mkdir(join(target,'blender'),{recursive:true});await writeFile(f,'fake');return{fbx_path:f}}},unityProvider:{exportAndValidate:async()=>{calls.unity++;const dir=join(target,'unity');await mkdir(dir,{recursive:true});await writeFile(join(dir,'import_validation.json'),'{}');return{pass:true}}}})});
  const result=await app.startFullProduction(project),reference=(await registry.list())[0],report=JSON.parse(await readFile(join(project,'references','reference_report.json'),'utf8'));assert.equal(result.result.final_state,'READY');assert.equal(result.state.checkpoint.stages.REFERENCE_PROCESSING.status,'COMPLETE');assert.equal(reference.source_type,'WEB');assert.equal(reference.license,'CC0');assert.ok(existsSync(reference.local_path));assert.equal(report.approved,1);assert.equal(provider.searches,1);assert.equal(provider.fetches,1);assert.equal(provider.normalizes,1);assert.equal(calls.http,3);assert.deepEqual(calls,{http:3,asset:1,material:1,blender:1,export:1,unity:1});
});